import { Category, Product, Collection, Banner, Coupon, StoreSettings, Review } from "@/types";

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat_handbags",
    slug: "handbags",
    name: "All Handbags",
    tagline: "Haute Maroquinerie & Everyday Luxury",
    description: "Discover the complete atelier collection of handcrafted leather silhouettes, structured bucket bags, and timeless totes.",
    image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw0c35245a/images/hi-res/2026-L6-CK2-10160273-A-29-1.jpg?sw=600&q=80",
    hero_image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw76953c89/images/hi-res/2026-L6-CK2-10160273-A-29-3.jpg?sw=1600&q=80",
    display_order: 1,
    is_active: true,
  },
  {
    id: "cat_bucket",
    slug: "bucket-bags",
    name: "Bucket Bags",
    tagline: "Sculptural Two-Way Silhouettes",
    description: "Architectural bucket shapes engineered with functional dual slip pockets and versatile two-way carry straps.",
    image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw0c35245a/images/hi-res/2026-L6-CK2-10160273-A-29-1.jpg?sw=600&q=80",
    hero_image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw76953c89/images/hi-res/2026-L6-CK2-10160273-A-29-3.jpg?sw=1600&q=80",
    display_order: 2,
    is_active: true,
  },
  {
    id: "cat_shoulder",
    slug: "shoulder-bags",
    name: "Shoulder Bags",
    tagline: "Chic Chain & Leather Statements",
    description: "Sleek, feminine shoulder bags with gleaming metal chain straps and quilted artisanal textures.",
    image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw964a5235/images/hi-res/2024-L7-CK2-20160191-A-D1-1.jpg?sw=600&q=80",
    hero_image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwe3385828/images/hi-res/2026-L6-CK2-90840669-IO-1.jpg?sw=1600&q=80",
    display_order: 3,
    is_active: true,
  },
  {
    id: "cat_tote",
    slug: "tote-bags",
    name: "Tote & Bowling Bags",
    tagline: "Spacious Refinement for Daily Sophistication",
    description: "Roomy elongated profiles with structured handles and polished metal accents for boardroom-to-evening style.",
    image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw7fbbfeaf/images/hi-res/2026-L6-CK2-30271780-A-J8-1.jpg?sw=600&q=80",
    hero_image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw8e564c20/images/hi-res/2026-L6-CK2-30160259-A-D1-1.jpg?sw=1600&q=80",
    display_order: 4,
    is_active: true,
  },
  {
    id: "cat_hobo",
    slug: "hobo-bags",
    name: "Hobo Bags",
    tagline: "Relaxed Curves & Slouch Elegance",
    description: "Supple, effortless silhouettes crafted from rich textured faux nappa leather with secure top magnetic closures.",
    image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwb79f2c0e/images/hi-res/2026-L6-CK2-40840659-A-J8-1.jpg?sw=600&q=80",
    hero_image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw80ec3886/images/hi-res/2026-L6-SL2-40782941-14-1.jpg?sw=1600&q=80",
    display_order: 5,
    is_active: true,
  },
  {
    id: "cat_crossbody",
    slug: "crossbody-bags",
    name: "Crossbody Bags",
    tagline: "Hands-Free Femininity & Evening Allure",
    description: "Petite, statement-making compact silhouettes with decorative ruching, bows, and adjustable shoulder cords.",
    image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw8fe2f596/images/hi-res/2026-L6-CK2-50671909-N5-1.jpg?sw=600&q=80",
    hero_image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw8fe2f596/images/hi-res/2026-L6-CK2-50671909-N5-1.jpg?sw=1600&q=80",
    display_order: 6,
    is_active: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // 1. HERO MOCK ITEM (Extracted from Charles & Keith India reference)
  {
    id: "prod_noane_bucket",
    slug: "noane-side-pocket-bucket-bag",
    name: "Noane Side-Pocket Two-Way Bucket Bag",
    subtitle: "Atelier Handbag Capsule • Style # CK2-10160273-A",
    short_description: "A sculptural two-way bucket bag crafted in supple faux nappa leather, featuring functional dual exterior side pockets, a structured top handle, and a detachable crossbody strap.",
    full_description: "Defined by its architectural bucket silhouette and functional design, the Noane bucket bag is an everyday luxury essential. Fitted with quick-access side pockets for essentials, this versatile silhouette transitions seamlessly from hand-held carry to hands-free crossbody styling with its adjustable strap. Finished with discreet gold-tone hardware and magnetic snap closure.",
    category_slug: "bucket-bags",
    category_id: "cat_bucket",
    base_price: 14999,
    sale_price: 12999,
    is_new: true,
    is_bestseller: true,
    is_featured: true,
    is_published: true,
    rating: 4.9,
    review_count: 38,
    stock_quantity: 45,
    sku: "CK2-10160273-A",
    created_at: new Date().toISOString(),
    primary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw0c35245a/images/hi-res/2026-L6-CK2-10160273-A-29-1.jpg?sw=1152&q=80",
    secondary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw76953c89/images/hi-res/2026-L6-CK2-10160273-A-29-3.jpg?sw=1152&q=80",
    images: [
      {
        id: "img_noane_1",
        product_id: "prod_noane_bucket",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw0c35245a/images/hi-res/2026-L6-CK2-10160273-A-29-1.jpg?sw=1152&q=80",
        alt_text: "Noane Bucket Bag - Front Silhouette Profile",
        display_order: 1,
        is_primary: true,
      },
      {
        id: "img_noane_2",
        product_id: "prod_noane_bucket",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw8374d6f8/images/hi-res/2026-L6-CK2-10160273-A-29-2.jpg?sw=1152&q=80",
        alt_text: "Noane Bucket Bag - Side Profile with Dual Slip Pockets",
        display_order: 2,
        is_primary: false,
      },
      {
        id: "img_noane_3",
        product_id: "prod_noane_bucket",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw76953c89/images/hi-res/2026-L6-CK2-10160273-A-29-3.jpg?sw=1152&q=80",
        alt_text: "Noane Bucket Bag - On-Model Editorial Styling",
        display_order: 3,
        is_primary: false,
      },
      {
        id: "img_noane_4",
        product_id: "prod_noane_bucket",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw20253457/images/hi-res/2026-L6-CK2-10160273-A-29-4.jpg?sw=1152&q=80",
        alt_text: "Noane Bucket Bag - Interior Lining & Zipper Pocket",
        display_order: 4,
        is_primary: false,
      },
      {
        id: "img_noane_5",
        product_id: "prod_noane_bucket",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw45c6198c/images/hi-res/2026-L6-CK2-10160273-A-29-5.jpg?sw=1152&q=80",
        alt_text: "Noane Bucket Bag - Base Protective Studs & Hardware Detail",
        display_order: 5,
        is_primary: false,
      },
    ],
    variants: [
      {
        id: "var_noane_brw",
        product_id: "prod_noane_bucket",
        sku: "CK2-10160273-A-BRW",
        color_name: "Dark Brown",
        color_hex: "#3E2723",
        size: "Medium",
        price_adjustment: 0,
        stock: 18,
        in_stock: true,
      },
      {
        id: "var_noane_noir",
        product_id: "prod_noane_bucket",
        sku: "CK2-10160273-A-NOIR",
        color_name: "Noir Black",
        color_hex: "#1A1A1A",
        size: "Medium",
        price_adjustment: 0,
        stock: 15,
        in_stock: true,
      },
      {
        id: "var_noane_chalk",
        product_id: "prod_noane_bucket",
        sku: "CK2-10160273-A-CHALK",
        color_name: "Chalk Cream",
        color_hex: "#E8E4D9",
        size: "Medium",
        price_adjustment: 0,
        stock: 12,
        in_stock: true,
      },
    ],
    details: [
      "Depth: 14 cm, Width: 24 cm, Height: 22 cm",
      "Single top handle (Handle drop: 12 cm)",
      "Detachable, adjustable shoulder strap (Length: 100–115 cm)",
      "Dual exterior side slip pockets for phone or cardholder",
      "Magnetic clasp closure with interior zipper compartment",
      "Material: Premium Textured Faux Nappa Leather",
      "Lining: Soft Microfiber Suede",
      "Bottom base protective metal studs",
    ],
    care_instructions: "Wipe clean with a soft, damp cloth. Keep away from direct heat and direct sunlight. Store in the complimentary D'NORA dust bag when not in use.",
    shipping_info: "Complimentary Pan-India White Glove Express Delivery (2-4 business days). 7-day hassle-free boutique return & exchange.",
    tags: ["Bucket Bag", "Bestseller", "New Arrival", "Two-Way", "Faux Leather"],
  },

  // 2. Rachel Denim Front-Pocket Chain Shoulder Bag
  {
    id: "prod_rachel_shoulder",
    slug: "rachel-denim-chain-shoulder-bag",
    name: "Rachel Denim Front-Pocket Chain Shoulder Bag",
    subtitle: "Fall Runway Edition • Style # CK2-20160191-A",
    short_description: "A compact structured shoulder bag crafted from washed denim with polished gold-tone hardware, an exterior flap pocket, and an interwoven chain shoulder strap.",
    full_description: "Channeling casual elegance, the Rachel chain shoulder bag pairs durable washed indigo denim with polished brass accents. Sized perfectly for cocktail evenings and city strolls, it features a secure turn-lock closure and an interior zip wall pocket.",
    category_slug: "shoulder-bags",
    category_id: "cat_shoulder",
    base_price: 11999,
    sale_price: 9999,
    is_new: true,
    is_bestseller: false,
    is_featured: true,
    is_published: true,
    rating: 4.8,
    review_count: 22,
    stock_quantity: 28,
    sku: "CK2-20160191-A",
    created_at: new Date().toISOString(),
    primary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw964a5235/images/hi-res/2024-L7-CK2-20160191-A-D1-1.jpg?sw=1152&q=80",
    secondary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw8e564c20/images/hi-res/2026-L6-CK2-30160259-A-D1-1.jpg?sw=1152&q=80",
    images: [
      {
        id: "img_rachel_1",
        product_id: "prod_rachel_shoulder",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw964a5235/images/hi-res/2024-L7-CK2-20160191-A-D1-1.jpg?sw=1152&q=80",
        alt_text: "Rachel Denim Chain Shoulder Bag - Front",
        display_order: 1,
        is_primary: true,
      },
    ],
    variants: [
      {
        id: "var_rachel_denim",
        product_id: "prod_rachel_shoulder",
        sku: "CK2-20160191-A-BLU",
        color_name: "Denim Blue",
        color_hex: "#4A6B82",
        size: "Small",
        price_adjustment: 0,
        stock: 20,
        in_stock: true,
      },
      {
        id: "var_rachel_noir",
        product_id: "prod_rachel_shoulder",
        sku: "CK2-20160191-A-NOIR",
        color_name: "Washed Charcoal",
        color_hex: "#2E2E2E",
        size: "Small",
        price_adjustment: 0,
        stock: 8,
        in_stock: true,
      },
    ],
    details: [
      "Depth: 8 cm, Width: 22 cm, Height: 15 cm",
      "Gold-finish curb chain strap (Drop: 28 cm)",
      "Front exterior flap pocket with turn-lock",
      "Material: Washed Cotton Denim & Faux Leather trim",
      "Interior zip compartment",
    ],
    care_instructions: "Spot clean with denim-safe cleaner. Avoid prolonged moisture contact.",
    shipping_info: "Complimentary Pan-India Express Delivery (2-4 business days).",
    tags: ["Shoulder Bag", "Denim", "Chain Strap", "New Arrival"],
  },

  // 3. Vega Elongated Bowling Bag
  {
    id: "prod_vega_bowling",
    slug: "vega-elongated-bowling-bag",
    name: "Vega Elongated Bowling Bag",
    subtitle: "Modernist Handbag Capsule • Style # CK2-30271780-A",
    short_description: "An elongated East-West bowling silhouette featuring sleek double tubular top handles, extended two-way zip closure, and structured bottom piping.",
    full_description: "The Vega elongated bowling bag reimagines retro athletic luxury for the contemporary woman. Its sleek cylindrical East-West silhouette offers generous space for sunglasses, cosmetics, and everyday gadgets while maintaining a sharp profile.",
    category_slug: "tote-bags",
    category_id: "cat_tote",
    base_price: 13999,
    sale_price: 11999,
    is_new: true,
    is_bestseller: true,
    is_featured: true,
    is_published: true,
    rating: 4.9,
    review_count: 19,
    stock_quantity: 32,
    sku: "CK2-30271780-A",
    created_at: new Date().toISOString(),
    primary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw7fbbfeaf/images/hi-res/2026-L6-CK2-30271780-A-J8-1.jpg?sw=1152&q=80",
    secondary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwb79f2c0e/images/hi-res/2026-L6-CK2-40840659-A-J8-1.jpg?sw=1152&q=80",
    images: [
      {
        id: "img_vega_1",
        product_id: "prod_vega_bowling",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw7fbbfeaf/images/hi-res/2026-L6-CK2-30271780-A-J8-1.jpg?sw=1152&q=80",
        alt_text: "Vega Elongated Bowling Bag - Front Silhouette",
        display_order: 1,
        is_primary: true,
      },
    ],
    variants: [
      {
        id: "var_vega_noir",
        product_id: "prod_vega_bowling",
        sku: "CK2-30271780-A-NOIR",
        color_name: "Noir Black",
        color_hex: "#1A1A1A",
        size: "Small",
        price_adjustment: 0,
        stock: 22,
        in_stock: true,
      },
      {
        id: "var_vega_cognac",
        product_id: "prod_vega_bowling",
        sku: "CK2-30271780-A-COG",
        color_name: "Cognac Amber",
        color_hex: "#7A3E1D",
        size: "Small",
        price_adjustment: 0,
        stock: 10,
        in_stock: true,
      },
    ],
    details: [
      "Depth: 11 cm, Width: 28 cm, Height: 13 cm",
      "Double rolled tubular handles (Drop: 14 cm)",
      "Extended two-way zip top closure",
      "Material: Ultra-smooth Faux Nappa Leather",
      "Reinforced base with metal foot studs",
    ],
    care_instructions: "Clean with dry microfiber cloth. Avoid sharp objects.",
    shipping_info: "Complimentary Express Pan-India Delivery.",
    tags: ["Bowling Bag", "East West", "Bestseller"],
  },

  // 4. Vega Hobo Bag
  {
    id: "prod_vega_hobo",
    slug: "vega-hobo-bag",
    name: "Vega Hobo Bag",
    subtitle: "Modernist Atelier Series • Style # CK2-40840659-A",
    short_description: "A relaxed, curved crescent hobo bag featuring an integrated shoulder strap, hidden magnetic clasp, and butter-soft textured vegan leather.",
    full_description: "The Vega Hobo Bag sculpts an organic crescent silhouette that tucks comfortably under the arm. Minimalist paneling and a clean interior give this bag a sleek modern feel suited for both boardroom attire and weekend city escapades.",
    category_slug: "hobo-bags",
    category_id: "cat_hobo",
    base_price: 12999,
    sale_price: 11499,
    is_new: false,
    is_bestseller: true,
    is_featured: true,
    is_published: true,
    rating: 4.8,
    review_count: 27,
    stock_quantity: 36,
    sku: "CK2-40840659-A",
    created_at: new Date().toISOString(),
    primary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwb79f2c0e/images/hi-res/2026-L6-CK2-40840659-A-J8-1.jpg?sw=1152&q=80",
    secondary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw7fbbfeaf/images/hi-res/2026-L6-CK2-30271780-A-J8-1.jpg?sw=1152&q=80",
    images: [
      {
        id: "img_hobo_1",
        product_id: "prod_vega_hobo",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwb79f2c0e/images/hi-res/2026-L6-CK2-40840659-A-J8-1.jpg?sw=1152&q=80",
        alt_text: "Vega Hobo Bag - Front Silhouette",
        display_order: 1,
        is_primary: true,
      },
    ],
    variants: [
      {
        id: "var_hobo_noir",
        product_id: "prod_vega_hobo",
        sku: "CK2-40840659-A-NOIR",
        color_name: "Noir Black",
        color_hex: "#1A1A1A",
        size: "Medium",
        price_adjustment: 0,
        stock: 24,
        in_stock: true,
      },
      {
        id: "var_hobo_blue",
        product_id: "prod_vega_hobo",
        sku: "CK2-40840659-A-BLU",
        color_name: "Smoky Blue",
        color_hex: "#5A7282",
        size: "Medium",
        price_adjustment: 0,
        stock: 12,
        in_stock: true,
      },
    ],
    details: [
      "Depth: 9 cm, Width: 26 cm, Height: 18 cm",
      "Ergonomic shoulder strap (Drop: 22 cm)",
      "Concealed magnetic snap top closure",
      "Material: Supple Vegan Nappa Leather",
      "Interior zip pocket and card slot",
    ],
    care_instructions: "Wipe with damp cloth and dry immediately.",
    shipping_info: "Pan-India complimentary delivery included.",
    tags: ["Hobo Bag", "Crescent", "Bestseller"],
  },

  // 5. Delfina Quilted Chain-Strap Shoulder Bag
  {
    id: "prod_delfina_quilted",
    slug: "delfina-quilted-chain-shoulder-bag",
    name: "Delfina Quilted Chain-Strap Shoulder Bag",
    subtitle: "High-Craftsmanship Capsule • Style # CK2-90840669-IO",
    short_description: "An opulent geometric quilted shoulder bag detailed with a sliding gold chain strap, turn-lock clasp, and double interior bellows compartments.",
    full_description: "Exquisite diagonal diamond quilting bestows the Delfina bag with undeniable haute couture prestige. Its sliding gold chain strap allows effortless transition from double-shoulder carry to a long crossbody drape.",
    category_slug: "shoulder-bags",
    category_id: "cat_shoulder",
    base_price: 16999,
    sale_price: 14999,
    is_new: true,
    is_bestseller: true,
    is_featured: true,
    is_published: true,
    rating: 5.0,
    review_count: 31,
    stock_quantity: 20,
    sku: "CK2-90840669-IO",
    created_at: new Date().toISOString(),
    primary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwe3385828/images/hi-res/2026-L6-CK2-90840669-IO-1.jpg?sw=1152&q=80",
    secondary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw964a5235/images/hi-res/2024-L7-CK2-20160191-A-D1-1.jpg?sw=1152&q=80",
    images: [
      {
        id: "img_delfina_1",
        product_id: "prod_delfina_quilted",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwe3385828/images/hi-res/2026-L6-CK2-90840669-IO-1.jpg?sw=1152&q=80",
        alt_text: "Delfina Quilted Chain-Strap Shoulder Bag - Front",
        display_order: 1,
        is_primary: true,
      },
    ],
    variants: [
      {
        id: "var_delfina_beige",
        product_id: "prod_delfina_quilted",
        sku: "CK2-90840669-IO-BGE",
        color_name: "Sand Beige",
        color_hex: "#D9CEBE",
        size: "Medium",
        price_adjustment: 0,
        stock: 12,
        in_stock: true,
      },
      {
        id: "var_delfina_noir",
        product_id: "prod_delfina_quilted",
        sku: "CK2-90840669-IO-NOIR",
        color_name: "Noir Black",
        color_hex: "#1A1A1A",
        size: "Medium",
        price_adjustment: 0,
        stock: 8,
        in_stock: true,
      },
    ],
    details: [
      "Depth: 9 cm, Width: 25 cm, Height: 16 cm",
      "Sliding dual-way curb chain strap (Drop: 29–52 cm)",
      "Artisanal geometric diamond quilting",
      "Material: Supple Vegan Leather with Silk-feel interior",
      "Signature atelier metallic push-lock",
    ],
    care_instructions: "Protect from abrasive surfaces. Store in dustbag.",
    shipping_info: "Pan-India complimentary express shipping with tracking.",
    tags: ["Quilted Bag", "Chain Strap", "Luxury", "New Arrival"],
  },

  // 6. Leather Top-Flap Hobo Bag
  {
    id: "prod_leather_top_flap",
    slug: "leather-top-flap-hobo-bag",
    name: "Leather Top-Flap Hobo Bag",
    subtitle: "Artisanal Collection • Style # SL2-40782941-14",
    short_description: "A genuine fine-grain leather hobo featuring a sculptural magnetic front flap, polished gold clasp, and rich taupe leather craft.",
    full_description: "The pinnacle of modern minimalism, this top-flap hobo is tailored from full-grain bovine leather with burnished edge finishing. Its roomy interior comfortably accommodates tablets, wallets, and cosmetics.",
    category_slug: "hobo-bags",
    category_id: "cat_hobo",
    base_price: 21999,
    sale_price: 18999,
    is_new: false,
    is_bestseller: true,
    is_featured: true,
    is_published: true,
    rating: 5.0,
    review_count: 44,
    stock_quantity: 15,
    sku: "SL2-40782941-14",
    created_at: new Date().toISOString(),
    primary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw80ec3886/images/hi-res/2026-L6-SL2-40782941-14-1.jpg?sw=1152&q=80",
    secondary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwb79f2c0e/images/hi-res/2026-L6-CK2-40840659-A-J8-1.jpg?sw=1152&q=80",
    images: [
      {
        id: "img_flap_1",
        product_id: "prod_leather_top_flap",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw80ec3886/images/hi-res/2026-L6-SL2-40782941-14-1.jpg?sw=1152&q=80",
        alt_text: "Leather Top-Flap Hobo Bag - Front",
        display_order: 1,
        is_primary: true,
      },
    ],
    variants: [
      {
        id: "var_flap_taupe",
        product_id: "prod_leather_top_flap",
        sku: "SL2-40782941-14-TPE",
        color_name: "Warm Taupe",
        color_hex: "#8C7B70",
        size: "Medium",
        price_adjustment: 0,
        stock: 9,
        in_stock: true,
      },
      {
        id: "var_flap_noir",
        product_id: "prod_leather_top_flap",
        sku: "SL2-40782941-14-NOIR",
        color_name: "Noir Black",
        color_hex: "#1A1A1A",
        size: "Medium",
        price_adjustment: 0,
        stock: 6,
        in_stock: true,
      },
    ],
    details: [
      "Depth: 10 cm, Width: 27 cm, Height: 20 cm",
      "Material: 100% Genuine Full-Grain Leather",
      "Sculptural fold-over flap with magnetic clasp",
      "Gold-tone hardware with subtle atelier engravings",
      "Lining: Premium Microfiber Suede",
    ],
    care_instructions: "Condition every 6 months with leather balm. Keep protected from moisture.",
    shipping_info: "Pan-India VIP White-Glove Courier Delivery.",
    tags: ["Genuine Leather", "Hobo Bag", "Collection"],
  },

  // 7. Mini Zephyr Tassel Tote Bag
  {
    id: "prod_zephyr_tote",
    slug: "mini-zephyr-tassel-tote-bag",
    name: "Mini Zephyr Tassel Tote Bag",
    subtitle: "Atelier Resort Collection • Style # CK2-30782930-09",
    short_description: "A compact structured tote bag crafted with playful leather tassels, tubular top handles, and a detachable shoulder strap.",
    full_description: "The Mini Zephyr tote captures playful luxury in a versatile compact frame. Adorned with delicate tassel charms and crisp contrast piping, it can be styled as a petite top-handle bag or worn crossbody.",
    category_slug: "tote-bags",
    category_id: "cat_tote",
    base_price: 13999,
    sale_price: 11999,
    is_new: true,
    is_bestseller: false,
    is_featured: true,
    is_published: true,
    rating: 4.7,
    review_count: 14,
    stock_quantity: 25,
    sku: "CK2-30782930-09",
    created_at: new Date().toISOString(),
    primary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwb76f4742/images/hi-res/2026-L6-CK2-30782930-09-1.jpg?sw=1152&q=80",
    secondary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw7fbbfeaf/images/hi-res/2026-L6-CK2-30271780-A-J8-1.jpg?sw=1152&q=80",
    images: [
      {
        id: "img_zephyr_1",
        product_id: "prod_zephyr_tote",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwb76f4742/images/hi-res/2026-L6-CK2-30782930-09-1.jpg?sw=1152&q=80",
        alt_text: "Mini Zephyr Tassel Tote Bag - Front",
        display_order: 1,
        is_primary: true,
      },
    ],
    variants: [
      {
        id: "var_zephyr_cream",
        product_id: "prod_zephyr_tote",
        sku: "CK2-30782930-09-CRM",
        color_name: "Chalk Cream",
        color_hex: "#F5F1E6",
        size: "Small",
        price_adjustment: 0,
        stock: 15,
        in_stock: true,
      },
      {
        id: "var_zephyr_tan",
        product_id: "prod_zephyr_tote",
        sku: "CK2-30782930-09-TAN",
        color_name: "Saddle Tan",
        color_hex: "#A3683A",
        size: "Small",
        price_adjustment: 0,
        stock: 10,
        in_stock: true,
      },
    ],
    details: [
      "Depth: 9 cm, Width: 21 cm, Height: 17 cm",
      "Double top handles (Drop: 10 cm)",
      "Detachable crossbody strap (Length: 110 cm)",
      "Handcrafted leather tassel pendant",
      "Magnetic closure with interior slip pockets",
    ],
    care_instructions: "Store in dustbag when not in use. Spot clean only.",
    shipping_info: "Complimentary Pan-India shipping.",
    tags: ["Tote Bag", "Tassel", "New"],
  },

  // 8. Reese Ruched Bow Top Handle Bag
  {
    id: "prod_reese_ruched",
    slug: "reese-ruched-bow-top-handle-bag",
    name: "Reese Ruched Bow Top Handle Bag",
    subtitle: "Atelier Evening Collection • Style # CK2-50671909-N5",
    short_description: "A whimsical, ultra-feminine miniature evening bag styled with dramatic ruching, a soft knotted bow handle, and a detachable metal crossbody chain.",
    full_description: "The Reese evening bag makes every entrance memorable. Featuring hand-pleated soft leather ruching and a sculpted bow accent, it holds your phone, cards, and favorite lipstick with whimsical grandeur.",
    category_slug: "crossbody-bags",
    category_id: "cat_crossbody",
    base_price: 11999,
    sale_price: 10499,
    is_new: true,
    is_bestseller: false,
    is_featured: true,
    is_published: true,
    rating: 4.9,
    review_count: 17,
    stock_quantity: 18,
    sku: "CK2-50671909-N5",
    created_at: new Date().toISOString(),
    primary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw8fe2f596/images/hi-res/2026-L6-CK2-50671909-N5-1.jpg?sw=1152&q=80",
    secondary_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwe3385828/images/hi-res/2026-L6-CK2-90840669-IO-1.jpg?sw=1152&q=80",
    images: [
      {
        id: "img_reese_1",
        product_id: "prod_reese_ruched",
        url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw8fe2f596/images/hi-res/2026-L6-CK2-50671909-N5-1.jpg?sw=1152&q=80",
        alt_text: "Reese Ruched Bow Bag - Front Profile",
        display_order: 1,
        is_primary: true,
      },
    ],
    variants: [
      {
        id: "var_reese_pink",
        product_id: "prod_reese_ruched",
        sku: "CK2-50671909-N5-PNK",
        color_name: "Soft Ballet Pink",
        color_hex: "#E8C4C4",
        size: "Small",
        price_adjustment: 0,
        stock: 10,
        in_stock: true,
      },
      {
        id: "var_reese_noir",
        product_id: "prod_reese_ruched",
        sku: "CK2-50671909-N5-NOIR",
        color_name: "Noir Velvet",
        color_hex: "#1A1A1A",
        size: "Small",
        price_adjustment: 0,
        stock: 8,
        in_stock: true,
      },
    ],
    details: [
      "Depth: 7 cm, Width: 19 cm, Height: 13 cm",
      "Ruched bow handle (Drop: 8 cm)",
      "Detachable fine curb chain (Length: 105 cm)",
      "Material: Ruched Faux Nappa Leather",
      "Concealed magnetic snap flap closure",
    ],
    care_instructions: "Handle gently. Store inside soft protective sleeve.",
    shipping_info: "Complimentary Pan-India express delivery.",
    tags: ["Evening Bag", "Ruched", "Bow", "Crossbody"],
  },
];

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: "col_autumn_winter",
    slug: "autumn-winter-capsule",
    name: "Autumn/Winter Haute Maroquinerie",
    tagline: "Sculptural forms, architectural bucket silhouettes & warm earthy leathers",
    description: "An homage to modern structural minimalism, engineered for effortless styling from daytime meetings to gala evenings.",
    image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw76953c89/images/hi-res/2026-L6-CK2-10160273-A-29-3.jpg?sw=1200&q=80",
    product_ids: ["prod_noane_bucket", "prod_vega_bowling", "prod_delfina_quilted", "prod_leather_top_flap"],
    is_active: true,
  },
];

export const INITIAL_BANNERS: Banner[] = [
  {
    id: "banner_1",
    title: "The Autumn Handbag Capsule",
    subtitle: "Explore the new sculptural Noane bucket bag and quilted leather silhouettes crafted for timeless distinction.",
    cta_text: "Shop The Collection",
    cta_link: "/shop",
    desktop_image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw76953c89/images/hi-res/2026-L6-CK2-10160273-A-29-3.jpg?sw=1920&q=85",
    mobile_image_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw76953c89/images/hi-res/2026-L6-CK2-10160273-A-29-3.jpg?sw=800&q=85",
    display_order: 1,
    is_active: true,
    type: "hero",
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: "coup_dnora10",
    code: "DNORA10",
    description: "10% privilege on orders over ₹5,000",
    discount_type: "percentage",
    discount_value: 10,
    min_cart_value: 5000,
    start_date: new Date().toISOString(),
    end_date: new Date(Date.now() + 90 * 86400000).toISOString(),
    usage_limit: 1000,
    times_used: 12,
    is_active: true,
  },
];

export const DEFAULT_STORE_SETTINGS: StoreSettings = {
  brand_name: "D'NORA",
  currency: "INR",
  currency_symbol: "₹",
  free_shipping_threshold: 5000,
  standard_shipping_fee: 0,
  express_shipping_fee: 450,
  tax_percentage: 18,
  contact_email: "concierge@dnora.luxury",
  concierge_phone: "+91 98765 43210",
  announcement_text: "COMPLIMENTARY PAN-INDIA EXPRESS DELIVERY ON ALL LUXURY HANDBAGS | 100% SECURE CHECKOUT",
};

export const INITIAL_STORE_SETTINGS = DEFAULT_STORE_SETTINGS;

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev_1",
    product_id: "prod_noane_bucket",
    user_name: "Ananya Singhania",
    user_email: "ananya.s@luxuryclient.in",
    rating: 5,
    title: "The silhouette is pure perfection",
    comment: "The Noane bucket bag exceeded all expectations. The leather feels astonishingly supple, and the side pockets comfortably fit my iPhone Pro Max and card sleeve. The Dark Brown shade matches everything.",
    verified_purchase: true,
    status: "approved",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "rev_2",
    product_id: "prod_noane_bucket",
    user_name: "Radhika Mehra",
    user_email: "radhika.m@mumbaiclub.com",
    rating: 5,
    title: "Elegant two-way carry",
    comment: "Love switching between the top handle for meetings and the crossbody strap when running errands in Mumbai. The packaging arrived with beautiful dust bag presentation.",
    verified_purchase: true,
    status: "approved",
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
];
