import { StyleReel } from "@/types";

/**
 * SEEN ON YOU - Real Customer & Stylist Reels Data
 */
export const INITIAL_STYLE_REELS: StyleReel[] = [
  {
    id: "reel_1",
    creator_name: "Ananya Singhania",
    creator_handle: "@ananya_styling",
    caption: "Styling the Noane Two-Way Bucket Bag with a monochrome cream linen set. The grain texture is sublime! ✨",
    video_url: "/videos/hero-banner.mp4",
    poster_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw76953c89/images/hi-res/2026-L6-CK2-10160273-A-29-3.jpg?sw=1152&q=80",
    likes_count: "2.4K",
    numeric_likes: 2420,
    display_order: 1,
    is_active: true,
    product_id: "prod_noane_bucket",
    product_slug: "noane-side-pocket-bucket-bag",
    product_name: "Noane Side-Pocket Two-Way Bucket Bag",
    product_price: 12999,
    product_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw0c35245a/images/hi-res/2026-L6-CK2-10160273-A-29-1.jpg?sw=1152&q=80",
    comments: [
      {
        id: "c1",
        user_name: "Meera Kapoor",
        comment: "The finish on this bucket bag looks so rich in real light! 😍",
        created_at: "2h ago",
      },
      {
        id: "c2",
        user_name: "Tanya Sen",
        comment: "Does it hold an iPhone Pro Max in the side pocket comfortably?",
        created_at: "5h ago",
      },
    ],
  },
  {
    id: "reel_2",
    creator_name: "Ria Kapoor",
    creator_handle: "@ria_k_lookbook",
    caption: "Airport OOTD featuring the Vega Bowling Bag in rich Noir. Holds my iPad, wallet, and essentials with ease. ✈️🖤",
    video_url: "/videos/hero-banner.mp4",
    poster_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw964a5235/images/hi-res/2024-L7-CK2-20160191-A-D1-1.jpg?sw=1152&q=80",
    likes_count: "3.8K",
    numeric_likes: 3840,
    display_order: 2,
    is_active: true,
    product_id: "prod_vega_bowling",
    product_slug: "vega-elongated-bowling-bag",
    product_name: "Vega Elongated Bowling Bag",
    product_price: 14499,
    product_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw964a5235/images/hi-res/2024-L7-CK2-20160191-A-D1-1.jpg?sw=1152&q=80",
    comments: [
      {
        id: "c3",
        user_name: "Sanya Roy",
        comment: "The bowling silhouette is pure 90s vintage revival! Love it.",
        created_at: "1d ago",
      },
    ],
  },
  {
    id: "reel_3",
    creator_name: "Tanvi Sharma",
    creator_handle: "@tanvisharma.diaries",
    caption: "Brunch fit check with the Mini Zephyr Tote! The artisanal tassel detail adds the dreamiest Parisian flair. 🥂",
    video_url: "/videos/hero-banner.mp4",
    poster_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw7fbbfeaf/images/hi-res/2026-L6-CK2-30271780-A-J8-1.jpg?sw=1152&q=80",
    likes_count: "1.9K",
    numeric_likes: 1910,
    display_order: 3,
    is_active: true,
    product_id: "prod_mini_zephyr",
    product_slug: "mini-zephyr-tassel-tote-bag",
    product_name: "Mini Zephyr Tassel Tote Bag",
    product_price: 11999,
    product_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw7fbbfeaf/images/hi-res/2026-L6-CK2-30271780-A-J8-1.jpg?sw=1152&q=80",
    comments: [
      {
        id: "c4",
        user_name: "Deepika Verma",
        comment: "The mini tote proportions are absolute perfection 🤎",
        created_at: "3h ago",
      },
    ],
  },
  {
    id: "reel_4",
    creator_name: "Pooja Mehta",
    creator_handle: "@poojam_curates",
    caption: "Boardroom to evening gala: structured elegance with the Celeste Satchel. Truly built like haute maroquinerie.",
    video_url: "/videos/hero-banner.mp4",
    poster_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwb79f2c0e/images/hi-res/2026-L6-CK2-40840659-A-J8-1.jpg?sw=1152&q=80",
    likes_count: "4.1K",
    numeric_likes: 4120,
    display_order: 4,
    is_active: true,
    product_id: "prod_celeste_satchel",
    product_slug: "celeste-top-handle-satchel",
    product_name: "Celeste Top-Handle Structured Satchel",
    product_price: 13999,
    product_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwb79f2c0e/images/hi-res/2026-L6-CK2-40840659-A-J8-1.jpg?sw=1152&q=80",
    comments: [],
  },
  {
    id: "reel_5",
    creator_name: "Simran V.",
    creator_handle: "@simran.v_couture",
    caption: "Weekend gallery stroll with the Aura Crossbody. Compact yet fits my essentials flawlessly. 🤍",
    video_url: "/videos/hero-banner.mp4",
    poster_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwe3385828/images/hi-res/2026-L6-CK2-90840669-IO-1.jpg?sw=1152&q=80",
    likes_count: "2.7K",
    numeric_likes: 2750,
    display_order: 5,
    is_active: true,
    product_id: "prod_aura_trapeze",
    product_slug: "aura-trapeze-crossbody-bag",
    product_name: "Aura Trapeze Crossbody Bag",
    product_price: 10999,
    product_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dwe3385828/images/hi-res/2026-L6-CK2-90840669-IO-1.jpg?sw=1152&q=80",
    comments: [],
  },
  {
    id: "reel_6",
    creator_name: "Kavya Desai",
    creator_handle: "@kavya_desai_fashion",
    caption: "Workday carry made luxurious with the Clara Monogram Tote. Fits my MacBook Pro effortlessly! 👜✨",
    video_url: "/videos/hero-banner.mp4",
    poster_url: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw80ec3886/images/hi-res/2026-L6-SL2-40782941-14-1.jpg?sw=1152&q=80",
    likes_count: "3.5K",
    numeric_likes: 3510,
    display_order: 6,
    is_active: true,
    product_id: "prod_clara_tote",
    product_slug: "clara-monogram-tote-bag",
    product_name: "Clara Monogram Daily Tote Bag",
    product_price: 16499,
    product_image: "https://www.charleskeith.in/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-in-products/default/dw80ec3886/images/hi-res/2026-L6-SL2-40782941-14-1.jpg?sw=1152&q=80",
    comments: [],
  },
];
